title: Hello, world! I'm Rohan Mallya.
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Rohan Mallya # add your name
author-img: my.jpg # add your photo
about-author:  # add description
# social-twitter: # add your Twitter handle
social-facebook: notrohanmallya # add your Facebook handle
social-github: rohanrmallya # add your Github handle
social-linkedin: rohanmallya # add your Linkedin handle
social-email: bangalorerohan@gmail.com # add your Email address



# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/blog/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
